package pt.ipg.mcm;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class Criptografia extends JFrame {
  private JLabel lbEncriptada;
  private JLabel lbOriginal;
  private JButton btEncriptar;
  private JTextField tfEncriptada;
  private JTextField tfOriginal;
  private JButton btDesencriptar;
  private JLabel lbDesencriptada;
  private JTextField tfDesencriptada;
  private JPanel rootPanel;
  private JLabel lbChave;
  private JTextField tfChave;


  public Criptografia() throws HeadlessException {
    super("Criptografia");
    setContentPane(rootPanel);
    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    pack();
    setVisible(true);

    btEncriptar.addActionListener(new AbstractAction() {
      @Override
      public void actionPerformed(ActionEvent e) {
        Encripter encripter = new Encripter(tfOriginal.getText().getBytes(), tfChave.getText().getBytes());
        encripter.encript();
        tfEncriptada.setText(new String(encripter.getMsg()));
      }
    });

    btDesencriptar.addActionListener(new AbstractAction() {
      @Override
      public void actionPerformed(ActionEvent e) {
        Decripter decripter = new Decripter(tfEncriptada.getText().getBytes(), tfChave.getText().getBytes());
        decripter.decript();
        tfDesencriptada.setText(new String(decripter.getMsg()));
      }
    });

  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    rootPanel = new JPanel();
    rootPanel.setLayout(new GridBagLayout());
    lbOriginal = new JLabel();
    lbOriginal.setText("Mensagem Original");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.EAST;
    rootPanel.add(lbOriginal, gbc);
    lbEncriptada = new JLabel();
    lbEncriptada.setText("Mensagem Encriptada");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.EAST;
    rootPanel.add(lbEncriptada, gbc);
    btEncriptar = new JButton();
    btEncriptar.setText("Encriptar");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 4;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    rootPanel.add(btEncriptar, gbc);
    tfEncriptada = new JTextField();
    tfEncriptada.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.gridwidth = 2;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    rootPanel.add(tfEncriptada, gbc);
    tfOriginal = new JTextField();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.gridwidth = 2;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    rootPanel.add(tfOriginal, gbc);
    btDesencriptar = new JButton();
    btDesencriptar.setText("Desencriptar");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 4;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    rootPanel.add(btDesencriptar, gbc);
    lbDesencriptada = new JLabel();
    lbDesencriptada.setText("Mensagem Desencriptada");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.EAST;
    rootPanel.add(lbDesencriptada, gbc);
    tfDesencriptada = new JTextField();
    tfDesencriptada.setColumns(0);
    tfDesencriptada.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.gridwidth = 2;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    rootPanel.add(tfDesencriptada, gbc);
    lbChave = new JLabel();
    lbChave.setText("Chave");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.EAST;
    rootPanel.add(lbChave, gbc);
    tfChave = new JTextField();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.gridwidth = 2;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    rootPanel.add(tfChave, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return rootPanel;
  }
}
