package pt.ipg.mcm;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class Criptografia extends JFrame {
  private JLabel lbEncriptada;
  private JLabel lbOriginal;
  private JButton btEncriptar;
  private JButton btDesencriptar;
  private JLabel lbDesencriptada;
  private JPanel rootPanel;
  private JLabel lbChave;
  private JTextArea taMsgOriginal;
  private JTextArea taMsgDesencriptada;
  private JTextArea taMsgEncriptad;
  private JTextArea taChave;


  public Criptografia() throws HeadlessException {
    super("Criptografia");
    setContentPane(rootPanel);
    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    pack();
    setVisible(true);

    btEncriptar.addActionListener(new AbstractAction() {
      @Override
      public void actionPerformed(ActionEvent e) {
        byte[] msgOriginal = taMsgOriginal.getText().getBytes();
        byte[] chave = taChave.getText().getBytes();
        if (chave.length == 0) {
          JOptionPane.showMessageDialog(Criptografia.this, "O campo chave não pode ser vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
          Encripter encripter = new Encripter(taMsgOriginal.getText().getBytes(), taChave.getText().getBytes());
          encripter.encript();
          taMsgEncriptad.setText(new String(encripter.getMsg()));
        }
      }
    });

    btDesencriptar.addActionListener(new AbstractAction() {
      @Override
      public void actionPerformed(ActionEvent e) {
        Decripter decripter = new Decripter(taMsgEncriptad.getText().getBytes(), taChave.getText().getBytes());
        decripter.decript();
        taMsgDesencriptada.setText(new String(decripter.getMsg()));
      }
    });

  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    rootPanel = new JPanel();
    rootPanel.setLayout(new GridBagLayout());
    lbOriginal = new JLabel();
    lbOriginal.setText("Mensagem Original");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.EAST;
    rootPanel.add(lbOriginal, gbc);
    lbEncriptada = new JLabel();
    lbEncriptada.setText("Mensagem Encriptada");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.EAST;
    rootPanel.add(lbEncriptada, gbc);
    btEncriptar = new JButton();
    btEncriptar.setText("Encriptar");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 4;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    rootPanel.add(btEncriptar, gbc);
    btDesencriptar = new JButton();
    btDesencriptar.setText("Desencriptar");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 4;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    rootPanel.add(btDesencriptar, gbc);
    lbDesencriptada = new JLabel();
    lbDesencriptada.setText("Mensagem Desencriptada");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.EAST;
    rootPanel.add(lbDesencriptada, gbc);
    lbChave = new JLabel();
    lbChave.setText("Chave");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.EAST;
    rootPanel.add(lbChave, gbc);
    taMsgOriginal = new JTextArea();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.BOTH;
    gbc.insets = new Insets(10, 10, 10, 10);
    rootPanel.add(taMsgOriginal, gbc);
    taChave = new JTextArea();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.BOTH;
    gbc.insets = new Insets(10, 10, 10, 10);
    rootPanel.add(taChave, gbc);
    taMsgEncriptad = new JTextArea();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.BOTH;
    gbc.insets = new Insets(10, 10, 10, 10);
    rootPanel.add(taMsgEncriptad, gbc);
    taMsgDesencriptada = new JTextArea();
    taMsgDesencriptada.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.BOTH;
    gbc.insets = new Insets(10, 10, 10, 10);
    rootPanel.add(taMsgDesencriptada, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return rootPanel;
  }
}
